quarkus.http.port=8083
quarkus.application.name=order-service

#API CLIENT
quarkus.rest-client.api-client.url=http://localhost:8082
quarkus.rest-client.api-client.connect-timeout=5000
quarkus.rest-client.api-client.read-timeout=5000

quarkus.smallrye-health.root-path=/api/health

#BD POSTGRESQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/retail_x_bd

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.database.generation=drop-and-create

#KAFKA CONFIGURATION
mp.messaging.outgoing.orders-out.connector=smallrye-kafka
mp.messaging.outgoing.orders-out.topic=orders
mp.messaging.outgoing.orders-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.orders-out.bootstrap.servers=localhost:29092


mp.messaging.outgoing.orders-cancel.connector=smallrye-kafka
mp.messaging.outgoing.orders-cancel.topic=orders-cancel
mp.messaging.outgoing.orders-cancel.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.orders-cancel.bootstrap.servers=localhost:29092

#DESACTIVA KAFKA DEV SERVICES
quarkus.devservices.enabled=false
quarkus.kafka.devservices.enabled=false


#CIRCUIT BREAKER
mp.fault.tolerance.retry.maxRetries=2
mp.fault.tolerance.retry.delay=1000
mp.fault.tolerance.retry.maxDuration=4000

# Timeout global
mp.fault.tolerance.timeout.value=2000

# Circuit Breaker global
mp.fault.tolerance.circuit-breaker.failureRatio=0.5
mp.fault.tolerance.circuit-breaker.delay=5000
mp.fault.tolerance.circuit-breaker.requestVolumeThreshold=4
mp.fault.tolerance.circuit-breaker.successThreshold=2


